# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false
  
- task: CopyPublishBuildArtifacts@1
  inputs:
    Contents: '**'
    ArtifactName: 'html'
    ArtifactType: 'Container'
- task: AzureStaticWebApp@0
  inputs:
    app_location: '$(build.sourcesDirectory)'
    output_location: '$(build.sourcesDirectory)'
    deployment_environment: Production
    azure_static_web_apps_api_token: $(deployement_token)